name: Statuses

on:
  schedule:
    - cron:  '0 17 * * 0'
  workflow_dispatch:
  push:
    branches:
      - '**/**'
jobs:
  statuses:
    name: Statuses
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - id: run-check-statuses
      run: python3 ./utils/status-action/check_statuses.py
    - uses: JasonEtco/create-an-issue@v2
      if: ${{ steps.run-check-statuses.outputs.MISSING_STATUSES_COUNT > 0 }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        filename: .github/ISSUE_TEMPLATE/update-statuses.md
